= Glossarist desktop -- cross-platform standardized terminology editor

image:https://img.shields.io/badge/commitizen-friendly-brightgreen.svg[alt="Commitizen friendly",link="http://commitizen.github.io/cz-cli/"] image:https://github.com/glossarist/glossarist-desktop/workflows/Build/release/badge.svg[alt="Build/release"]

This application allows to collaboratively edit concept systems in Glossarist format.

Currently those are:

. Editing https://github.com/ISO-TC211/geolexica-database[ISO/TC 211 Geolexica database] data
. Editing https://github.com/geolexica/osgeo-glossary[OSGeo Geolexica database] data
. (PoC) Editing https://github.com/glossarist/iev-data[IEC Electropedia data] data

See more at https://glossarist.org/desktop/.

== Contributing

PRs are welcome.

=== Committing

This repository is set up with AngularJS commit message convention.
Pre-commit hook will invoke interactive prompt, powered by Commitizen,
that will ask you for information and put together a commit message for you.

To follow the convention:

* Only use ``git commit`` when making commits
* Don’t use built-in IDE commit prompts, since they may bypass prepare-commit-msg hook

=== Pulling

- It is recommended to use “rebase” behavior of pull (make sure to use fresh Git)
  by having this in your global .gitconfig:

  ```
  [pull]
          rebase = true
  ```

- When pulling, Commitizen commit prompt may appear even if there is no merge commit to be made.
  You can dismiss it with Ctrl+C.

=== Pushing

There is a pre-push Git hook that compiles the app.
This helps us catch compilation errors before code reaches CI.
